### ISSUE TITLE
Missing documentation and example

### ISSUE THREAD

**Issue by iltar** [hostnet/entity-plugin-lib#15]
Currently the documentation only tells you how to install and how to run it. It would be really neat to implement some more documentation:
- How to enable composition for a relation between 2 entities in 2 packages
- How to enable optional composition
- `composer.json` regarding suggest and require
- Trait (file)names
- Conventions
- What you have to do to include the composed code
- etc.

**Comment by nicoschoenmaker** [comment]
@iltar does the [cheatsheet](https://hostnet.github.io/entity-plugin-lib/) fix your issues? It is linked at the bottom of the readme, as well.

**Comment by iltar** [comment]
It provides a very, very basic example, far from sufficient for anybody to start using this package.
