### ISSUE TITLE
Replace "@var Generated\" by "@var " in ReflectionMethod.php

### ISSUE THREAD

**Issue by iltar** [hostnet/entity-plugin-lib#30]
https://github.com/hostnet/entity-plugin-lib/blob/master/src/ReflectionMethod.php#L48-L51

The problem is that while being in the `Generated` namespace, it will still refer to `Generated\MyInterface` for example. This makes your IDE think it's located in `Generated\Generated` which is false.

**Comment by yannickl88** [comment]
should be fixed now
