### ISSUE TITLE
Tests fail on PHP 7.2

### ISSUE THREAD

**Issue by jesse-hostnet** [hostnet/entity-plugin-lib#56]
The test suite currently fails for PHP 7.2.

Since Travis is configured to run the test suite for PHP up to 7.1, this isn't immediately obvious.
Test failures:

> 1) Hostnet\Component\EntityPlugin\ReflectionGeneratorTest::testGenerateWithReturnType
> Failed asserting that two strings are identical.
> --- Expected
> +++ Actual
> @@ @@
> --   public function objectMethod(): \Hostnet\Component\EntityPlugin\Fixtures\object;
> ++   public function objectMethod(): \object;
> 
> /home/jtabourel/projects/entity-plugin-lib/test/ReflectionGeneratorTest.php:183
> 
> 2) Hostnet\Component\EntityPlugin\ReflectionGeneratorTest::testGenerateWithExtendedReturnType
> Failed asserting that two strings are identical.
> --- Expected
> +++ Actual
> @@ @@
> --   public function objectMethod(): ?\Hostnet\Component\EntityPlugin\Fixtures\object;
> ++   public function objectMethod(): ?\object;
> 

Presumably, the failure is due to the support for the `object` return type hint that was introduced in 7.2.

**Comment by svandervlugt** [comment]
Fixed with https://github.com/hostnet/entity-plugin-lib/pull/58
